version: '3.8'

services:
  mongo-enem:
    image: mongo:latest
    container_name: mongo-enem
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ProjetoMBA123
    volumes:
      - mongo_dados:/data/db

volumes:
  mongo_dados:
